In [3]:
import pandas as pd

lp = pd.read_csv('LOCAL_PEOPLE_2020.csv', index_col=[0,1,2])
lf = pd.read_csv('LONG_FOREIGNER_2020.csv', index_col=[0,1,2])
tf = pd.read_csv('TEMPORARY_FOREIGNER_2020.csv', index_col=[0,1,2])

lp

                             총생활인구수  남자0세부터9세생활인구수  남자10세부터14세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110  248283.0355      6496.6713        3519.7135
                 11140  187720.0184      4655.7791        1817.9263
                 11170  292640.2683      7594.5578        3783.8774
                 11200  333267.7444     12520.2471        5415.8134
                 11215  390059.2798     12015.7622        6462.2537
...                             ...            ...              ...
2020-12-31 23    11620  491876.3992     12042.7597        5878.9457
                 11650  466368.7220     18594.7954       10289.7404
                 11680  621348.1084     23088.1736       14923.8699
                 11710  724883.1371     29325.6824       15030.9786
                 11740  524891.9605     20670.5419       11726.7471

                        남자15세부터19세생활인구수  남자20세부터24세생활인구수  남자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        6348.0673       12253.9712       12938.7039
                 11140        3500.9994        7226.0512        9428.2194
                 11170        6324.2591       11834.2528       15891.0504
                 11200        7182.9770       10466.6080       13383.5771
                 11215       12038.9403       16338.6258       18367.5701
...                                 ...              ...              ...
2020-12-31 23    11620        9286.4932       18595.6889       32894.0641
                 11650       13522.5719       12280.9308       14460.0631
                 11680       20251.4996       16558.2360       22027.7269
                 11710       19885.0444       18608.1647       24941.9716
                 11740       14516.8545       12868.8571       16480.5157

                        남자30세부터34세생활인구수  남자35세부터39세생활인구수  남자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9583.1787        9696.6035        8895.0342
                 11140        8787.5163        9442.4510        8264.1337
                 11170       14739.2364       15018.9060       11916.5552
                 11200       13654.5821       15978.9277       13432.2342
                 11215       15746.9044       16093.9988       13784.4168
...                                 ...              ...              ...
2020-12-31 23    11620       27029.4913       23753.7566       19202.5323
                 11650       15802.6365       19491.3479       21583.5104
                 11680       23573.7027       28369.1445       28567.3817
                 11710       27706.8890       33383.4961       30549.4414
                 11740       17984.3031       22281.0699       22180.4172

                        남자45세부터49세생활인구수  ...  여자35세부터39세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2020-01-01 0     11110       10752.8266  ...        8607.0974
                 11140        8377.4505  ...        8308.9521
                 11170       12483.4437  ...       13667.5186
                 11200       13956.0427  ...       15999.6087
                 11215       15565.8778  ...       16085.3865
...                                 ...  ...              ...
2020-12-31 23    11620       20569.7617  ...       20053.8085
                 11650       24169.1925  ...       22045.1812
                 11680       31866.4770  ...       28815.1006
                 11710       31112.3173  ...       35057.7094
                 11740       22753.6294  ...       23417.6348

                        여자40세부터44세생활인구수  여자45세부터49세생활인구수  여자50세부터54세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        8011.5248        9875.9187        8486.6664
                 11140        6605.4908        7053.0874        5983.3255
                 11170       10514.6813       11290.0344        8829.6365
                 11200       12892.9772       13062.3169       11207.5851
                 11215       13892.6067       15360.7202       14039.0758
...                                 ...              ...              ...
2020-12-31 23    11620       16635.8672       17106.8235       15356.6362
                 11650       22204.0968       21985.7829       16723.0522
                 11680       29317.1204       30446.5162       21103.6165
                 11710       30684.7583       31200.3182       26635.7275
                 11740       21581.9854       22339.4273       19779.8662

                        여자55세부터59세생활인구수  여자60세부터64세생활인구수  여자65세부터69세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9490.4589        8222.0645        6400.1665
                 11140        6620.2703        5915.9446        4544.3436
                 11170        9709.4967        8643.7729        6371.5681
                 11200       12904.2161       11578.6985        8481.8560
                 11215       14903.7537       13224.1186        9307.2924
...                                 ...              ...              ...
2020-12-31 23    11620       17435.0351       15557.4030       13130.1839
                 11650       16226.4957       14851.4468       11578.7158
                 11680       20034.7712       18114.9466       14567.9752
                 11710       29853.7165       26337.6339       19556.6567
                 11740       22972.5990       20946.2449       15867.6609

                        여자70세이상생활인구수         요일   월
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110    17695.4216  Wednesday   1
                 11140    11603.8885  Wednesday   1
                 11170    18755.7771  Wednesday   1
                 11200    22570.1152  Wednesday   1
                 11215    22441.4454  Wednesday   1
...                              ...        ...  ..
2020-12-31 23    11620    30703.4738   Thursday  12
                 11650    27920.7343   Thursday  12
                 11680    34078.2136   Thursday  12
                 11710    40528.2835   Thursday  12
                 11740    33403.5613   Thursday  12

[219600 rows x 31 columns]

In [4]:
lp.drop(['총생활인구수', '요일', '월'], axis=1, inplace=True)
lp

                        남자0세부터9세생활인구수  남자10세부터14세생활인구수  남자15세부터19세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110      6496.6713        3519.7135        6348.0673
                 11140      4655.7791        1817.9263        3500.9994
                 11170      7594.5578        3783.8774        6324.2591
                 11200     12520.2471        5415.8134        7182.9770
                 11215     12015.7622        6462.2537       12038.9403
...                               ...              ...              ...
2020-12-31 23    11620     12042.7597        5878.9457        9286.4932
                 11650     18594.7954       10289.7404       13522.5719
                 11680     23088.1736       14923.8699       20251.4996
                 11710     29325.6824       15030.9786       19885.0444
                 11740     20670.5419       11726.7471       14516.8545

                        남자20세부터24세생활인구수  남자25세부터29세생활인구수  남자30세부터34세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110       12253.9712       12938.7039        9583.1787
                 11140        7226.0512        9428.2194        8787.5163
                 11170       11834.2528       15891.0504       14739.2364
                 11200       10466.6080       13383.5771       13654.5821
                 11215       16338.6258       18367.5701       15746.9044
...                                 ...              ...              ...
2020-12-31 23    11620       18595.6889       32894.0641       27029.4913
                 11650       12280.9308       14460.0631       15802.6365
                 11680       16558.2360       22027.7269       23573.7027
                 11710       18608.1647       24941.9716       27706.8890
                 11740       12868.8571       16480.5157       17984.3031

                        남자35세부터39세생활인구수  남자40세부터44세생활인구수  남자45세부터49세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9696.6035        8895.0342       10752.8266
                 11140        9442.4510        8264.1337        8377.4505
                 11170       15018.9060       11916.5552       12483.4437
                 11200       15978.9277       13432.2342       13956.0427
                 11215       16093.9988       13784.4168       15565.8778
...                                 ...              ...              ...
2020-12-31 23    11620       23753.7566       19202.5323       20569.7617
                 11650       19491.3479       21583.5104       24169.1925
                 11680       28369.1445       28567.3817       31866.4770
                 11710       33383.4961       30549.4414       31112.3173
                 11740       22281.0699       22180.4172       22753.6294

                        남자50세부터54세생활인구수  ...  여자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2020-01-01 0     11110        8729.0718  ...       11259.3854
                 11140        6822.9493  ...       10079.4077
                 11170        9924.5004  ...       16182.6128
                 11200       11498.3947  ...       13626.2653
                 11215       13117.1947  ...       18310.8330
...                                 ...  ...              ...
2020-12-31 23    11620       15640.4959  ...       28665.3905
                 11650       18379.3634  ...       15061.3760
                 11680       24670.0493  ...       23043.5160
                 11710       25195.2179  ...       27108.0002
                 11740       18138.4280  ...       17222.1333

                        여자30세부터34세생활인구수  여자35세부터39세생활인구수  여자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        8426.5599        8607.0974        8011.5248
                 11140        8195.3502        8308.9521        6605.4908
                 11170       13760.6577       13667.5186       10514.6813
                 11200       14261.8259       15999.6087       12892.9772
                 11215       16293.1891       16085.3865       13892.6067
...                                 ...              ...              ...
2020-12-31 23    11620       22176.0338       20053.8085       16635.8672
                 11650       17063.1982       22045.1812       22204.0968
                 11680       24573.9310       28815.1006       29317.1204
                 11710       29385.6601       35057.7094       30684.7583
                 11740       19317.6787       23417.6348       21581.9854

                        여자45세부터49세생활인구수  여자50세부터54세생활인구수  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9875.9187        8486.6664        9490.4589
                 11140        7053.0874        5983.3255        6620.2703
                 11170       11290.0344        8829.6365        9709.4967
                 11200       13062.3169       11207.5851       12904.2161
                 11215       15360.7202       14039.0758       14903.7537
...                                 ...              ...              ...
2020-12-31 23    11620       17106.8235       15356.6362       17435.0351
                 11650       21985.7829       16723.0522       16226.4957
                 11680       30446.5162       21103.6165       20034.7712
                 11710       31200.3182       26635.7275       29853.7165
                 11740       22339.4273       19779.8662       22972.5990

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        8222.0645        6400.1665    17695.4216
                 11140        5915.9446        4544.3436    11603.8885
                 11170        8643.7729        6371.5681    18755.7771
                 11200       11578.6985        8481.8560    22570.1152
                 11215       13224.1186        9307.2924    22441.4454
...                                 ...              ...           ...
2020-12-31 23    11620       15557.4030       13130.1839    30703.4738
                 11650       14851.4468       11578.7158    27920.7343
                 11680       18114.9466       14567.9752    34078.2136
                 11710       26337.6339       19556.6567    40528.2835
                 11740       20946.2449       15867.6609    33403.5613

[219600 rows x 28 columns]

In [5]:
lf.drop(['총생활인구수', '요일', '월'], axis=1, inplace=True)
tf.drop('총생활인구수', axis=1, inplace=True)

In [6]:
people = pd.concat([lp, lf, tf], axis=1)
people

                        남자0세부터9세생활인구수  남자10세부터14세생활인구수  남자15세부터19세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110      6496.6713        3519.7135        6348.0673
                 11140      4655.7791        1817.9263        3500.9994
                 11170      7594.5578        3783.8774        6324.2591
                 11200     12520.2471        5415.8134        7182.9770
                 11215     12015.7622        6462.2537       12038.9403
...                               ...              ...              ...
2020-12-31 23    11620     12042.7597        5878.9457        9286.4932
                 11650     18594.7954       10289.7404       13522.5719
                 11680     23088.1736       14923.8699       20251.4996
                 11710     29325.6824       15030.9786       19885.0444
                 11740     20670.5419       11726.7471       14516.8545

                        남자20세부터24세생활인구수  남자25세부터29세생활인구수  남자30세부터34세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110       12253.9712       12938.7039        9583.1787
                 11140        7226.0512        9428.2194        8787.5163
                 11170       11834.2528       15891.0504       14739.2364
                 11200       10466.6080       13383.5771       13654.5821
                 11215       16338.6258       18367.5701       15746.9044
...                                 ...              ...              ...
2020-12-31 23    11620       18595.6889       32894.0641       27029.4913
                 11650       12280.9308       14460.0631       15802.6365
                 11680       16558.2360       22027.7269       23573.7027
                 11710       18608.1647       24941.9716       27706.8890
                 11740       12868.8571       16480.5157       17984.3031

                        남자35세부터39세생활인구수  남자40세부터44세생활인구수  남자45세부터49세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9696.6035        8895.0342       10752.8266
                 11140        9442.4510        8264.1337        8377.4505
                 11170       15018.9060       11916.5552       12483.4437
                 11200       15978.9277       13432.2342       13956.0427
                 11215       16093.9988       13784.4168       15565.8778
...                                 ...              ...              ...
2020-12-31 23    11620       23753.7566       19202.5323       20569.7617
                 11650       19491.3479       21583.5104       24169.1925
                 11680       28369.1445       28567.3817       31866.4770
                 11710       33383.4961       30549.4414       31112.3173
                 11740       22281.0699       22180.4172       22753.6294

                        남자50세부터54세생활인구수  ...  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2020-01-01 0     11110        8729.0718  ...        9490.4589
                 11140        6822.9493  ...        6620.2703
                 11170        9924.5004  ...        9709.4967
                 11200       11498.3947  ...       12904.2161
                 11215       13117.1947  ...       14903.7537
...                                 ...  ...              ...
2020-12-31 23    11620       15640.4959  ...       17435.0351
                 11650       18379.3634  ...       16226.4957
                 11680       24670.0493  ...       20034.7712
                 11710       25195.2179  ...       29853.7165
                 11740       18138.4280  ...       22972.5990

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        8222.0645        6400.1665    17695.4216
                 11140        5915.9446        4544.3436    11603.8885
                 11170        8643.7729        6371.5681    18755.7771
                 11200       11578.6985        8481.8560    22570.1152
                 11215       13224.1186        9307.2924    22441.4454
...                                 ...              ...           ...
2020-12-31 23    11620       15557.4030       13130.1839    30703.4738
                 11650       14851.4468       11578.7158    27920.7343
                 11680       18114.9466       14567.9752    34078.2136
                 11710       26337.6339       19556.6567    40528.2835
                 11740       20946.2449       15867.6609    33403.5613

                          중국인체류인구수  중국외외국인체류인구수    중국인체류인구수  중국외외국인체류인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110  10379.4199    6209.1524   6743.2469    9407.5382
                 11140  11132.8623    6521.9530  22831.2897   32527.8093
                 11170   5565.1182   18655.2212   3701.8256    9778.9244
                 11200  10122.0467    7846.9778    836.8684    1440.6532
                 11215  19730.8466    5301.9199   1373.4035    1432.4875
...                            ...          ...         ...          ...
2020-12-31 23    11620  18634.5630    5505.7286   1526.9843     900.3448
                 11650   3640.8109    6332.6846    962.7291    1694.7838
                 11680   4977.1709    8640.3613   1464.1390    5083.1674
                 11710   8368.2917    5690.3419    549.0522    3371.2241
                 11740   6981.0408    2384.1208    549.0519     483.1716

                               요일     월
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110  Wednesday   1.0
                 11140  Wednesday   1.0
                 11170  Wednesday   1.0
                 11200  Wednesday   1.0
                 11215  Wednesday   1.0
...                           ...   ...
2020-12-31 23    11620   Thursday  12.0
                 11650   Thursday  12.0
                 11680   Thursday  12.0
                 11710   Thursday  12.0
                 11740   Thursday  12.0

[219600 rows x 34 columns]

In [7]:
people.drop(['남자0세부터9세생활인구수', '남자10세부터14세생활인구수', '여자0세부터9세생활인구수', '여자10세부터14세생활인구수'], axis=1, inplace=True)
people

                        남자15세부터19세생활인구수  남자20세부터24세생활인구수  남자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        6348.0673       12253.9712       12938.7039
                 11140        3500.9994        7226.0512        9428.2194
                 11170        6324.2591       11834.2528       15891.0504
                 11200        7182.9770       10466.6080       13383.5771
                 11215       12038.9403       16338.6258       18367.5701
...                                 ...              ...              ...
2020-12-31 23    11620        9286.4932       18595.6889       32894.0641
                 11650       13522.5719       12280.9308       14460.0631
                 11680       20251.4996       16558.2360       22027.7269
                 11710       19885.0444       18608.1647       24941.9716
                 11740       14516.8545       12868.8571       16480.5157

                        남자30세부터34세생활인구수  남자35세부터39세생활인구수  남자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        9583.1787        9696.6035        8895.0342
                 11140        8787.5163        9442.4510        8264.1337
                 11170       14739.2364       15018.9060       11916.5552
                 11200       13654.5821       15978.9277       13432.2342
                 11215       15746.9044       16093.9988       13784.4168
...                                 ...              ...              ...
2020-12-31 23    11620       27029.4913       23753.7566       19202.5323
                 11650       15802.6365       19491.3479       21583.5104
                 11680       23573.7027       28369.1445       28567.3817
                 11710       27706.8890       33383.4961       30549.4414
                 11740       17984.3031       22281.0699       22180.4172

                        남자45세부터49세생활인구수  남자50세부터54세생활인구수  남자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110       10752.8266        8729.0718        9514.1392
                 11140        8377.4505        6822.9493        7087.9241
                 11170       12483.4437        9924.5004        9195.5477
                 11200       13956.0427       11498.3947       12265.3807
                 11215       15565.8778       13117.1947       14090.8218
...                                 ...              ...              ...
2020-12-31 23    11620       20569.7617       15640.4959       15965.8145
                 11650       24169.1925       18379.3634       15825.3619
                 11680       31866.4770       24670.0493       19689.4110
                 11710       31112.3173       25195.2179       25714.1399
                 11740       22753.6294       18138.4280       19904.2873

                        남자60세부터64세생활인구수  ...  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2020-01-01 0     11110        7641.6487  ...        9490.4589
                 11140        5843.8084  ...        6620.2703
                 11170        7849.3562  ...        9709.4967
                 11200        9704.9096  ...       12904.2161
                 11215       11018.0310  ...       14903.7537
...                                 ...  ...              ...
2020-12-31 23    11620       12887.8688  ...       17435.0351
                 11650       12520.8504  ...       16226.4957
                 11680       14873.2280  ...       20034.7712
                 11710       21071.4009  ...       29853.7165
                 11740       16725.7478  ...       22972.5990

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110        8222.0645        6400.1665    17695.4216
                 11140        5915.9446        4544.3436    11603.8885
                 11170        8643.7729        6371.5681    18755.7771
                 11200       11578.6985        8481.8560    22570.1152
                 11215       13224.1186        9307.2924    22441.4454
...                                 ...              ...           ...
2020-12-31 23    11620       15557.4030       13130.1839    30703.4738
                 11650       14851.4468       11578.7158    27920.7343
                 11680       18114.9466       14567.9752    34078.2136
                 11710       26337.6339       19556.6567    40528.2835
                 11740       20946.2449       15867.6609    33403.5613

                          중국인체류인구수  중국외외국인체류인구수    중국인체류인구수  중국외외국인체류인구수  \
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110  10379.4199    6209.1524   6743.2469    9407.5382
                 11140  11132.8623    6521.9530  22831.2897   32527.8093
                 11170   5565.1182   18655.2212   3701.8256    9778.9244
                 11200  10122.0467    7846.9778    836.8684    1440.6532
                 11215  19730.8466    5301.9199   1373.4035    1432.4875
...                            ...          ...         ...          ...
2020-12-31 23    11620  18634.5630    5505.7286   1526.9843     900.3448
                 11650   3640.8109    6332.6846    962.7291    1694.7838
                 11680   4977.1709    8640.3613   1464.1390    5083.1674
                 11710   8368.2917    5690.3419    549.0522    3371.2241
                 11740   6981.0408    2384.1208    549.0519     483.1716

                               요일     월
기준일ID      시간대구분 자치구코드
2020-01-01 0     11110  Wednesday   1.0
                 11140  Wednesday   1.0
                 11170  Wednesday   1.0
                 11200  Wednesday   1.0
                 11215  Wednesday   1.0
...                           ...   ...
2020-12-31 23    11620   Thursday  12.0
                 11650   Thursday  12.0
                 11680   Thursday  12.0
                 11710   Thursday  12.0
                 11740   Thursday  12.0

[219600 rows x 30 columns]

In [8]:
people.to_csv('2020생활인구.csv')