In [7]:
import pandas as pd

lp = pd.read_csv('LOCAL_PEOPLE_2021.csv', index_col=[0,1,2])
lf = pd.read_csv('LONG_FOREIGNER_2021.csv', index_col=[0,1,2])
tf = pd.read_csv('TEMPORARY_FOREIGNER_2021.csv', index_col=[0,1,2])

lp

                             총생활인구수  남자0세부터9세생활인구수  남자10세부터14세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110  194924.6184      4920.3837        2992.2011
                 11140  148826.8808      3354.1662        1376.5528
                 11170  250141.2136      7083.5939        3542.5572
                 11200  315490.0745     11513.7075        4873.2608
                 11215  360268.0149     10668.3623        5764.4680
...                             ...            ...              ...
2021-12-31 23    11620  472514.0761     11459.7460        5587.5167
                 11650  455062.9561     19787.1947       10682.4784
                 11680  626466.4158     24454.1035       15836.2983
                 11710  712411.1104     30428.8846       15366.8198
                 11740  524319.2164     21095.4564       12006.9656

                        남자15세부터19세생활인구수  남자20세부터24세생활인구수  남자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        4479.0239        7799.4338        8270.0476
                 11140        2368.3576        4868.7237        6945.7261
                 11170        5294.7572        7602.9197        9970.4226
                 11200        6427.3620        9447.8712       12296.0848
                 11215        9216.3402       12610.7515       16765.3160
...                                 ...              ...              ...
2021-12-31 23    11620        9246.5077       18907.9663       31630.4011
                 11650       13954.8801       12218.0882       13859.9908
                 11680       21877.8836       17167.4107       21281.2474
                 11710       20377.0469       18965.2072       24192.2124
                 11740       14574.3609       13118.0621       16176.9547

                        남자30세부터34세생활인구수  남자35세부터39세생활인구수  남자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6591.1392        7579.7820        7074.5372
                 11140        6640.6784        7840.6110        6741.2837
                 11170       11424.4500       13636.9205       11185.3911
                 11200       12453.8504       15616.7389       13210.2964
                 11215       15174.9819       15309.0600       13867.0227
...                                 ...              ...              ...
2021-12-31 23    11620       25874.5206       22738.3801       18514.8420
                 11650       15248.2675       19129.0357       20563.1683
                 11680       22822.7317       28478.8064       28669.5597
                 11710       26429.5933       32640.2745       29971.1064
                 11740       17415.4066       22046.3803       21736.6823

                        남자45세부터49세생활인구수  ...  여자35세부터39세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2021-01-01 0     11110        8952.4622  ...        7281.9873
                 11140        6923.2649  ...        7244.8277
                 11170       11567.6748  ...       12831.7555
                 11200       13627.0795  ...       15997.2596
                 11215       14994.9732  ...       15679.1837
...                                 ...  ...              ...
2021-12-31 23    11620       19409.0945  ...       19093.2494
                 11650       23909.5492  ...       20992.0304
                 11680       32611.1781  ...       28196.1925
                 11710       31238.0179  ...       34237.0376
                 11740       22611.9155  ...       23594.2146

                        여자40세부터44세생활인구수  여자45세부터49세생활인구수  여자50세부터54세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        7159.4938        8479.3144        7389.4164
                 11140        5420.8522        5795.2854        4829.2206
                 11170       10190.8974       10715.4628        8839.3659
                 11200       12525.5609       12903.9998       10991.7768
                 11215       13760.7719       14761.8863       13689.3575
...                                 ...              ...              ...
2021-12-31 23    11620       15704.3718       16656.3598       15146.7999
                 11650       20998.7721       22433.3375       16798.5863
                 11680       28974.8318       31343.5098       21532.9109
                 11710       30491.9252       30678.1327       26101.4104
                 11740       21721.1200       22377.6210       19549.5054

                        여자55세부터59세생활인구수  여자60세부터64세생활인구수  여자65세부터69세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        8051.4425        6722.6436        5109.8562
                 11140        5617.3479        4846.5084        3847.0501
                 11170        9417.1985        8353.8373        5899.2935
                 11200       12442.7269       10785.3456        7925.9533
                 11215       14573.9438       12408.8341        8957.7143
...                                 ...              ...              ...
2021-12-31 23    11620       16492.3015       14879.3203       12008.2245
                 11650       15450.9244       13399.7482       11023.4122
                 11680       19701.3446       17174.8688       14571.0011
                 11710       28698.9175       24997.5744       19119.4128
                 11740       22154.7722       20360.2661       15934.1844

                        여자70세이상생활인구수      요일   월
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110    15036.7700  Friday   1
                 11140     9823.1857  Friday   1
                 11170    16888.6424  Friday   1
                 11200    20678.4090  Friday   1
                 11215    20651.2597  Friday   1
...                              ...     ...  ..
2021-12-31 23    11620    29786.2623  Friday  12
                 11650    26408.4854  Friday  12
                 11680    34306.4306  Friday  12
                 11710    40250.2444  Friday  12
                 11740    34850.0792  Friday  12

[219000 rows x 31 columns]

In [8]:
lp.drop(['총생활인구수', '요일', '월'], axis=1, inplace=True)
lp

                        남자0세부터9세생활인구수  남자10세부터14세생활인구수  남자15세부터19세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110      4920.3837        2992.2011        4479.0239
                 11140      3354.1662        1376.5528        2368.3576
                 11170      7083.5939        3542.5572        5294.7572
                 11200     11513.7075        4873.2608        6427.3620
                 11215     10668.3623        5764.4680        9216.3402
...                               ...              ...              ...
2021-12-31 23    11620     11459.7460        5587.5167        9246.5077
                 11650     19787.1947       10682.4784       13954.8801
                 11680     24454.1035       15836.2983       21877.8836
                 11710     30428.8846       15366.8198       20377.0469
                 11740     21095.4564       12006.9656       14574.3609

                        남자20세부터24세생활인구수  남자25세부터29세생활인구수  남자30세부터34세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        7799.4338        8270.0476        6591.1392
                 11140        4868.7237        6945.7261        6640.6784
                 11170        7602.9197        9970.4226       11424.4500
                 11200        9447.8712       12296.0848       12453.8504
                 11215       12610.7515       16765.3160       15174.9819
...                                 ...              ...              ...
2021-12-31 23    11620       18907.9663       31630.4011       25874.5206
                 11650       12218.0882       13859.9908       15248.2675
                 11680       17167.4107       21281.2474       22822.7317
                 11710       18965.2072       24192.2124       26429.5933
                 11740       13118.0621       16176.9547       17415.4066

                        남자35세부터39세생활인구수  남자40세부터44세생활인구수  남자45세부터49세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        7579.7820        7074.5372        8952.4622
                 11140        7840.6110        6741.2837        6923.2649
                 11170       13636.9205       11185.3911       11567.6748
                 11200       15616.7389       13210.2964       13627.0795
                 11215       15309.0600       13867.0227       14994.9732
...                                 ...              ...              ...
2021-12-31 23    11620       22738.3801       18514.8420       19409.0945
                 11650       19129.0357       20563.1683       23909.5492
                 11680       28478.8064       28669.5597       32611.1781
                 11710       32640.2745       29971.1064       31238.0179
                 11740       22046.3803       21736.6823       22611.9155

                        남자50세부터54세생활인구수  ...  여자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2021-01-01 0     11110        7640.1431  ...        7513.2691
                 11140        5651.1192  ...        7110.3397
                 11170        9636.9646  ...       10681.6414
                 11200       11083.1104  ...       12707.7943
                 11215       12818.5331  ...       17406.2677
...                                 ...  ...              ...
2021-12-31 23    11620       15593.4064  ...       27657.9259
                 11650       18381.2529  ...       14424.0264
                 11680       25448.3141  ...       23086.3151
                 11710       24981.9935  ...       25489.0412
                 11740       18411.0467  ...       17141.8310

                        여자30세부터34세생활인구수  여자35세부터39세생활인구수  여자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6532.6210        7281.9873        7159.4938
                 11140        6713.5499        7244.8277        5420.8522
                 11170       11129.4982       12831.7555       10190.8974
                 11200       13462.4842       15997.2596       12525.5609
                 11215       15460.2633       15679.1837       13760.7719
...                                 ...              ...              ...
2021-12-31 23    11620       20556.6298       19093.2494       15704.3718
                 11650       16067.1612       20992.0304       20998.7721
                 11680       23453.2183       28196.1925       28974.8318
                 11710       27829.3396       34237.0376       30491.9252
                 11740       18817.7341       23594.2146       21721.1200

                        여자45세부터49세생활인구수  여자50세부터54세생활인구수  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        8479.3144        7389.4164        8051.4425
                 11140        5795.2854        4829.2206        5617.3479
                 11170       10715.4628        8839.3659        9417.1985
                 11200       12903.9998       10991.7768       12442.7269
                 11215       14761.8863       13689.3575       14573.9438
...                                 ...              ...              ...
2021-12-31 23    11620       16656.3598       15146.7999       16492.3015
                 11650       22433.3375       16798.5863       15450.9244
                 11680       31343.5098       21532.9109       19701.3446
                 11710       30678.1327       26101.4104       28698.9175
                 11740       22377.6210       19549.5054       22154.7722

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6722.6436        5109.8562    15036.7700
                 11140        4846.5084        3847.0501     9823.1857
                 11170        8353.8373        5899.2935    16888.6424
                 11200       10785.3456        7925.9533    20678.4090
                 11215       12408.8341        8957.7143    20651.2597
...                                 ...              ...           ...
2021-12-31 23    11620       14879.3203       12008.2245    29786.2623
                 11650       13399.7482       11023.4122    26408.4854
                 11680       17174.8688       14571.0011    34306.4306
                 11710       24997.5744       19119.4128    40250.2444
                 11740       20360.2661       15934.1844    34850.0792

[219000 rows x 28 columns]

In [10]:
lf.drop(['총생활인구수', '요일', '월'], axis=1, inplace=True)
tf.drop('총생활인구수', axis=1, inplace=True)

In [11]:
people = pd.concat([lp, lf, tf], axis=1)
people

                        남자0세부터9세생활인구수  남자10세부터14세생활인구수  남자15세부터19세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110      4920.3837        2992.2011        4479.0239
                 11140      3354.1662        1376.5528        2368.3576
                 11170      7083.5939        3542.5572        5294.7572
                 11200     11513.7075        4873.2608        6427.3620
                 11215     10668.3623        5764.4680        9216.3402
...                               ...              ...              ...
2021-12-31 23    11620     11459.7460        5587.5167        9246.5077
                 11650     19787.1947       10682.4784       13954.8801
                 11680     24454.1035       15836.2983       21877.8836
                 11710     30428.8846       15366.8198       20377.0469
                 11740     21095.4564       12006.9656       14574.3609

                        남자20세부터24세생활인구수  남자25세부터29세생활인구수  남자30세부터34세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        7799.4338        8270.0476        6591.1392
                 11140        4868.7237        6945.7261        6640.6784
                 11170        7602.9197        9970.4226       11424.4500
                 11200        9447.8712       12296.0848       12453.8504
                 11215       12610.7515       16765.3160       15174.9819
...                                 ...              ...              ...
2021-12-31 23    11620       18907.9663       31630.4011       25874.5206
                 11650       12218.0882       13859.9908       15248.2675
                 11680       17167.4107       21281.2474       22822.7317
                 11710       18965.2072       24192.2124       26429.5933
                 11740       13118.0621       16176.9547       17415.4066

                        남자35세부터39세생활인구수  남자40세부터44세생활인구수  남자45세부터49세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        7579.7820        7074.5372        8952.4622
                 11140        7840.6110        6741.2837        6923.2649
                 11170       13636.9205       11185.3911       11567.6748
                 11200       15616.7389       13210.2964       13627.0795
                 11215       15309.0600       13867.0227       14994.9732
...                                 ...              ...              ...
2021-12-31 23    11620       22738.3801       18514.8420       19409.0945
                 11650       19129.0357       20563.1683       23909.5492
                 11680       28478.8064       28669.5597       32611.1781
                 11710       32640.2745       29971.1064       31238.0179
                 11740       22046.3803       21736.6823       22611.9155

                        남자50세부터54세생활인구수  ...  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2021-01-01 0     11110        7640.1431  ...        8051.4425
                 11140        5651.1192  ...        5617.3479
                 11170        9636.9646  ...        9417.1985
                 11200       11083.1104  ...       12442.7269
                 11215       12818.5331  ...       14573.9438
...                                 ...  ...              ...
2021-12-31 23    11620       15593.4064  ...       16492.3015
                 11650       18381.2529  ...       15450.9244
                 11680       25448.3141  ...       19701.3446
                 11710       24981.9935  ...       28698.9175
                 11740       18411.0467  ...       22154.7722

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6722.6436        5109.8562    15036.7700
                 11140        4846.5084        3847.0501     9823.1857
                 11170        8353.8373        5899.2935    16888.6424
                 11200       10785.3456        7925.9533    20678.4090
                 11215       12408.8341        8957.7143    20651.2597
...                                 ...              ...           ...
2021-12-31 23    11620       14879.3203       12008.2245    29786.2623
                 11650       13399.7482       11023.4122    26408.4854
                 11680       17174.8688       14571.0011    34306.4306
                 11710       24997.5744       19119.4128    40250.2444
                 11740       20360.2661       15934.1844    34850.0792

                          중국인체류인구수  중국외외국인체류인구수   중국인체류인구수  중국외외국인체류인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110   9209.1513    4950.6873   819.3381    1045.7867
                 11140   9103.3266    5040.5007  3246.5284    2159.2696
                 11170   3945.8324   15047.2872   565.5814    1570.2635
                 11200   9574.9486    4740.7469   921.3862    1902.0457
                 11215  17510.0955    4923.7750  1385.4227     750.4009
...                            ...          ...        ...          ...
2021-12-31 23    11620  16869.1665    5762.3148  2084.0490    2306.2449
                 11650   3315.8505    6005.3371   964.9808    4448.1318
                 11680   4496.3529    8322.4473  1560.9484    7061.1642
                 11710   7653.2445    6868.4785  1411.0500    3380.9156
                 11740   6742.9916    2490.9662   799.3748     834.5561

                            요일   월
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110  Friday   1
                 11140  Friday   1
                 11170  Friday   1
                 11200  Friday   1
                 11215  Friday   1
...                        ...  ..
2021-12-31 23    11620  Friday  12
                 11650  Friday  12
                 11680  Friday  12
                 11710  Friday  12
                 11740  Friday  12

[219000 rows x 34 columns]

In [12]:
people.drop(['남자0세부터9세생활인구수', '남자10세부터14세생활인구수', '여자0세부터9세생활인구수', '여자10세부터14세생활인구수'], axis=1, inplace=True)
people

                        남자15세부터19세생활인구수  남자20세부터24세생활인구수  남자25세부터29세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        4479.0239        7799.4338        8270.0476
                 11140        2368.3576        4868.7237        6945.7261
                 11170        5294.7572        7602.9197        9970.4226
                 11200        6427.3620        9447.8712       12296.0848
                 11215        9216.3402       12610.7515       16765.3160
...                                 ...              ...              ...
2021-12-31 23    11620        9246.5077       18907.9663       31630.4011
                 11650       13954.8801       12218.0882       13859.9908
                 11680       21877.8836       17167.4107       21281.2474
                 11710       20377.0469       18965.2072       24192.2124
                 11740       14574.3609       13118.0621       16176.9547

                        남자30세부터34세생활인구수  남자35세부터39세생활인구수  남자40세부터44세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6591.1392        7579.7820        7074.5372
                 11140        6640.6784        7840.6110        6741.2837
                 11170       11424.4500       13636.9205       11185.3911
                 11200       12453.8504       15616.7389       13210.2964
                 11215       15174.9819       15309.0600       13867.0227
...                                 ...              ...              ...
2021-12-31 23    11620       25874.5206       22738.3801       18514.8420
                 11650       15248.2675       19129.0357       20563.1683
                 11680       22822.7317       28478.8064       28669.5597
                 11710       26429.5933       32640.2745       29971.1064
                 11740       17415.4066       22046.3803       21736.6823

                        남자45세부터49세생활인구수  남자50세부터54세생활인구수  남자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        8952.4622        7640.1431        8004.5292
                 11140        6923.2649        5651.1192        5891.0733
                 11170       11567.6748        9636.9646        8836.9767
                 11200       13627.0795       11083.1104       12086.6203
                 11215       14994.9732       12818.5331       13426.8171
...                                 ...              ...              ...
2021-12-31 23    11620       19409.0945       15593.4064       15709.3527
                 11650       23909.5492       18381.2529       15664.7458
                 11680       32611.1781       25448.3141       20183.5066
                 11710       31238.0179       24981.9935       25115.9468
                 11740       22611.9155       18411.0467       19733.6562

                        남자60세부터64세생활인구수  ...  여자55세부터59세생활인구수  \
기준일ID      시간대구분 자치구코드                   ...
2021-01-01 0     11110        6378.7208  ...        8051.4425
                 11140        4755.8277  ...        5617.3479
                 11170        7127.7214  ...        9417.1985
                 11200        9302.3618  ...       12442.7269
                 11215       10354.3327  ...       14573.9438
...                                 ...  ...              ...
2021-12-31 23    11620       12271.5063  ...       16492.3015
                 11650       11428.9245  ...       15450.9244
                 11680       14243.6075  ...       19701.3446
                 11710       20280.2047  ...       28698.9175
                 11740       16425.8743  ...       22154.7722

                        여자60세부터64세생활인구수  여자65세부터69세생활인구수  여자70세이상생활인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110        6722.6436        5109.8562    15036.7700
                 11140        4846.5084        3847.0501     9823.1857
                 11170        8353.8373        5899.2935    16888.6424
                 11200       10785.3456        7925.9533    20678.4090
                 11215       12408.8341        8957.7143    20651.2597
...                                 ...              ...           ...
2021-12-31 23    11620       14879.3203       12008.2245    29786.2623
                 11650       13399.7482       11023.4122    26408.4854
                 11680       17174.8688       14571.0011    34306.4306
                 11710       24997.5744       19119.4128    40250.2444
                 11740       20360.2661       15934.1844    34850.0792

                          중국인체류인구수  중국외외국인체류인구수   중국인체류인구수  중국외외국인체류인구수  \
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110   9209.1513    4950.6873   819.3381    1045.7867
                 11140   9103.3266    5040.5007  3246.5284    2159.2696
                 11170   3945.8324   15047.2872   565.5814    1570.2635
                 11200   9574.9486    4740.7469   921.3862    1902.0457
                 11215  17510.0955    4923.7750  1385.4227     750.4009
...                            ...          ...        ...          ...
2021-12-31 23    11620  16869.1665    5762.3148  2084.0490    2306.2449
                 11650   3315.8505    6005.3371   964.9808    4448.1318
                 11680   4496.3529    8322.4473  1560.9484    7061.1642
                 11710   7653.2445    6868.4785  1411.0500    3380.9156
                 11740   6742.9916    2490.9662   799.3748     834.5561

                            요일   월
기준일ID      시간대구분 자치구코드
2021-01-01 0     11110  Friday   1
                 11140  Friday   1
                 11170  Friday   1
                 11200  Friday   1
                 11215  Friday   1
...                        ...  ..
2021-12-31 23    11620  Friday  12
                 11650  Friday  12
                 11680  Friday  12
                 11710  Friday  12
                 11740  Friday  12

[219000 rows x 30 columns]

In [13]:
people.to_csv('2021생활인구.csv')